### ISSUE TITLE
issue of sketch

### ISSUE THREAD

**Issue by wangclin** [kiddyboots216/CommEfficient#13]
hi, 
Sorry to bother you, but I have some problems when deploying Sketch.
I got 0 grad updates and 0 download bytes when I do me the second iteration. Could you please tell me what is the problem?
My hyperparameters are --dataset_dir data/cifar10 --tensorboard --local_batch_size 50  --dataset_name CIFAR10 --model ResNet9 --mode sketch --num_clients 200 --num_workers 10 --num_rows 1 --num_cols 50000 --error_type none --local_momentum 0.0  --virtual_momentum 0.9 --max_grad_norm 1.0

I think the problem maybe sketch.accumulateVec(grad), but I don't know how to modify it.

Thanks a lot.

**Comment by kiddyboots216** [comment]
Hi! I think you're going to want to specify --error_type virtual, can you try that and let me know if the bytes up/down columns are still 0?

**Comment by wangclin** [comment]
I tried error_type == virtual just now, and unfortunately, the bytes down are still 0. 
The hyper-parameters are --dataset_dir data/cifar10 --tensorboard --local_batch_size 50  --dataset_name CIFAR10 --model ResNet9 --mode sketch --num_clients 200 --num_workers 10 --num_rows 1 --num_cols 500000 --error_type virtual --local_momentum 0.0  --virtual_momentum 0.9

The cmd line shows {'train_time': 69.53465247154236, 'train_loss': 2.302894648551941, 'train_acc': 0.09535999777913094, 'test_loss': 2.302500894069672, 'test_acc': 0.10139999743551016, 'down (MiB)': 0, 'up (MiB)': 1907, 
'total_time': 72.22434043884277}

**Comment by wangclin** [comment]
thanks for helping me, I have addressed those issues. 
I changed the num_blocks to 1 in Csvec lib, and it helped.
